# Generated by Django 2.2.1 on 2019-07-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DFI_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source_Mac', models.CharField(max_length=17)),
                ('Dest_Mac', models.CharField(max_length=17)),
                ('Source_IP', models.CharField(max_length=15)),
                ('Dest_IP', models.CharField(max_length=15)),
                ('Source_Port', models.CharField(max_length=5)),
                ('Dest_Port', models.CharField(max_length=5)),
                ('Protocol', models.CharField(max_length=20)),
                ('Bytes', models.IntegerField()),
                ('Host', models.CharField(max_length=300)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DFI Info',
                'verbose_name_plural': 'DFI Info',
                'db_table': 'DFI_Info',
            },
        ),
        migrations.CreateModel(
            name='DPI_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source_IP', models.CharField(max_length=15)),
                ('Dest_IP', models.CharField(max_length=15)),
                ('Pic_Path', models.CharField(max_length=50)),
                ('DateTime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'DPI Picture',
                'verbose_name_plural': 'DPI Picture',
                'db_table': 'DPI_Picture',
            },
        ),
    ]
